package com.revature.Model;

import java.util.Objects;

public class Person {
    private int id;
    private String name;
    private boolean active;
    private long cell;

    /**
     * No args constructor
     * (same as the 'default' constructor)
     */
    public Person(){

    }

    /**
     * constructor
     * @param id
     * @param name
     * @param active
     * @param cell
     */
    public Person(int id, String name, boolean active, long cell) {
        this.id = id;
        this.name = name;
        this.active = active;
        this.cell = cell;
    }

    /**
     * getters and setters etc generated by the 'generate' menu in ide
     * @return
     */
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public long getCell() {
        return cell;
    }

    public void setCell(long cell) {
        this.cell = cell;
    }

    @Override
    public String toString() {
        return "Person{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", active=" + active +
                ", cell=" + cell +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Person person = (Person) o;
        return id == person.id && active == person.active && cell == person.cell && Objects.equals(name, person.name);
    }

    @Override
    public int hashCode() {
        Object obj = new Object();
        return Objects.hash(id, name, active, cell);
    }
}